from array import array

arr = array('i', [1, 2, 3, 4, 5])
print(arr[0])
print(arr[1])
arr.append(6)
print(arr)
arr.insert(2, 7)
print(arr)
arr.extend([8, 9, 10])
print(arr)
arr.remove(3)
print(arr)
arr.pop()
print(arr)
print(arr.index(4))
arr.reverse()
print(arr)
print(arr.buffer_info())
print(arr.count(2))
arr_list = arr.tolist()
print(arr_list)
sliced_arr = arr[1:4]
print(sliced_arr)
